version: '3.1'
services:
  redis:
    image: redis:5.0.9
    container_name: redis_container
    privileged: true
    restart: always
    volumes:
      - ./data:/data
      # - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      # - ./redis/redis.conf:/etc/redis/redis.conf
      # - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # command: ['redis-server', '/usr/local/etc/redis/redis.conf']
      # /var/log/redis/redis-server.log
      # - ./redis:/etc/redis
      # - ./log/redis:/var/log/redis
      # - ./usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    # command: ['redis-server', '/etc/redis/redis.conf']
    command: ['redis-server']
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    volumes:
      - ./config/conf.d:/etc/mysql/conf.d
      # - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
      ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: platform
    ports:
      - '3306:3306'
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
  nginx:
    image: nginx
    container_name: nginx_container
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx/logs:/var/log/nginx/logs
      - ./config/nginx/html:/usr/share/nginx/html
      # - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    ports:
      - 80:80
  # server:
  #   container_name: server_container
  #   volumes:
  #     - ./server:/server
  #     - /var/log/nginx/logs:/var/log/nginx
  #   build:
  #     context: ./server
  #     dockerfile: ./Dockerfile
  #   command /bin
  #   ports:
  #     - 3000:3000